<a href="https://colab.research.google.com/github/varmagsr/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import sys

# The Basics

In [17]:
a = np.array([1,2,3], dtype='int8')
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])


#print Matrix
print(a)
print(b)
print(a*b)
print(a+b)
# Get Dimension
print("Dimension",a.ndim)
print("Dimension",b.ndim)
#Get Shape
print("Shape", b.shape)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [ 4. 10. 18.]]
[[2. 4. 6.]
 [5. 7. 9.]]
Dimension 1
Dimension 2
Shape (2, 3)


In [19]:
#Get Type
print(a.dtype)
print(b.dtype)

int8
float64


In [20]:
#Get Size
print(a.itemsize)
print(b.itemsize)

1
8


In [6]:
#Get Total Size
print(a.size)
print(a.nbytes)

3
3


# Accessing/Changing specific elements, rows & Columns, etc

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get a specific element[r,c]
#a.shape
a[1,4]
#we can also us negitive array count
a[1,-2]

13

In [9]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [11]:
#Getting a little more fancy [Startindex:stepsize]
t = 1
v = -2
s = 2
a[0, t:v:s]

array([2, 4])

In [22]:
#Change specific array values
a[1,5] = 20
print(a)
#Change range of array values
a[1:5] = 123
print(a)

a[:,2] = [1,2]
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[  1   2   3   4   5   6   7]
 [123 123 123 123 123 123 123]]
[[  1   2   1   4   5   6   7]
 [123 123   2 123 123 123 123]]


# *3-Dimensional array example

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#Get specifiec element(work outside in)
#b[1,0,0]
b[:,1,1]


array([4, 8])

In [28]:
#Replacing the value in array
b[:,1,:] = [[9,1],[8,8]]
b

array([[[1, 2],
        [9, 1]],

       [[5, 6],
        [8, 8]]])

# Initializating Diffrent Types of arrays

In [32]:
#All 0s matrix
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [34]:
#All 1s matrix
np.ones((2,3,4),dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [35]:
#Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [37]:
#Any other number (full_like)
#np.full(a.shape,4)
#OR use below for same result
np.full_like(a,4)
# the below stracture came from the array a created in one of the above code lines.

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
#Random decimal numbers
np.random.rand(4,2,5)
#or
np.random.random_sample(a.shape)

array([[0.46791208, 0.96538557, 0.75234555, 0.32434477, 0.60868633,
        0.65219496, 0.833068  ],
       [0.01788769, 0.89328322, 0.69914802, 0.43084456, 0.07225929,
        0.55669872, 0.4386179 ]])

In [47]:
# Random integer values
np.random.randint(-3,7, size=(3,3))

array([[ 6,  6, -2],
       [ 4,  0,  5],
       [-2,  5,  6]])

In [48]:
# The Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [62]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))

z[1,1]=9
print(z)

output[1:4,1:4] = z # 4 is exclusive in the array so it will conisdered from 1 to 3
#or you can write the same as "output[1:-1,1:-1] = z"
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# #### Becarefull when copying array!!!

In [63]:
a = np.array([1,2,3])
b = a.copy() #if we don't use .copy() , values in a will also updated what ever in b.
b[0] = 100
print(a)

[1 2 3]


# ***Matchematics***

In [3]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [78]:
a + 2

array([3, 4, 5, 6])

In [70]:
#a += 2
#a

array([5, 6, 7, 8])

In [79]:
a - 2

array([-1,  0,  1,  2])

In [80]:
a * 2

array([2, 4, 6, 8])

In [81]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [82]:
b = np.array([2,2,4,4])
a + b

array([3, 4, 7, 8])

In [83]:
a ** 2

array([ 1,  4,  9, 16])

In [87]:
#np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##Liner Algebra

In [4]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # matrix multiplaction

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [5]:
# Find the Determinant
c =np.identity(3)
np.linalg.det(c)

1.0

# **#Statistics**

In [6]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats)

1

In [10]:
np.max(stats)

6

In [11]:
np.min(stats, axis=1)

array([1, 4])

In [15]:
np.max(stats, axis=1)

array([3, 6])

In [16]:
np.sum(stats)

21

In [17]:
np.sum(stats, axis=0)

array([5, 7, 9])

# ***##Reorganizing Arrays***

In [29]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2)) #before.reshape((8,1))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# #Vertically stacking vectors

In [31]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous
# Load Data

In [35]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

# Boolean Masking and Advance Indexing 

In [36]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [37]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [40]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [41]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [39]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [45]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])